# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/protos/agent_action.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'common/protos/agent_action.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protos.actions import (
  build_farm_action_pb2 as common_dot_protos_dot_actions_dot_build__farm__action__pb2,
)
from common.protos.actions import (
  build_house_action_pb2 as common_dot_protos_dot_actions_dot_build__house__action__pb2,
)
from common.protos.actions import (
  build_quarry_action_pb2 as common_dot_protos_dot_actions_dot_build__quarry__action__pb2,
)
from common.protos.actions import (
  drop_action_pb2 as common_dot_protos_dot_actions_dot_drop__action__pb2,
)
from common.protos.actions import (
  farm_action_pb2 as common_dot_protos_dot_actions_dot_farm__action__pb2,
)
from common.protos.actions import (
  mine_action_pb2 as common_dot_protos_dot_actions_dot_mine__action__pb2,
)
from common.protos.actions import (
  move_action_pb2 as common_dot_protos_dot_actions_dot_move__action__pb2,
)
from common.protos.actions import (
  pick_up_action_pb2 as common_dot_protos_dot_actions_dot_pick__up__action__pb2,
)

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n common/protos/agent_action.proto\x1a\'common/protos/actions/move_action.proto\x1a\'common/protos/actions/farm_action.proto\x1a*common/protos/actions/pick_up_action.proto\x1a\'common/protos/actions/drop_action.proto\x1a\'common/protos/actions/mine_action.proto\x1a.common/protos/actions/build_house_action.proto\x1a-common/protos/actions/build_farm_action.proto\x1a/common/protos/actions/build_quarry_action.proto\"\xf5\x02\n\x0b\x41gentAction\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\x05\x12\"\n\x0bmove_action\x18\x02 \x01(\x0b\x32\x0b.MoveActionH\x00\x12\"\n\x0b\x66\x61rm_action\x18\x03 \x01(\x0b\x32\x0b.FarmActionH\x00\x12\'\n\x0epick_up_action\x18\x04 \x01(\x0b\x32\r.PickUpActionH\x00\x12\"\n\x0b\x64rop_action\x18\x05 \x01(\x0b\x32\x0b.DropActionH\x00\x12\"\n\x0bmine_action\x18\x06 \x01(\x0b\x32\x0b.MineActionH\x00\x12/\n\x12\x62uild_house_action\x18\x07 \x01(\x0b\x32\x11.BuildHouseActionH\x00\x12-\n\x11\x62uild_farm_action\x18\x08 \x01(\x0b\x32\x10.BuildFarmActionH\x00\x12\x31\n\x13\x62uild_quarry_action\x18\t \x01(\x0b\x32\x12.BuildQuarryActionH\x00\x42\x08\n\x06\x61\x63tion\"3\n\x12\x41gentActionRequest\x12\x1d\n\x07\x61\x63tions\x18\x01 \x03(\x0b\x32\x0c.AgentActionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.protos.agent_action_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTACTION']._serialized_start=389
  _globals['_AGENTACTION']._serialized_end=762
  _globals['_AGENTACTIONREQUEST']._serialized_start=764
  _globals['_AGENTACTIONREQUEST']._serialized_end=815
# @@protoc_insertion_point(module_scope)
