# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/protos/actions/move_action.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'common/protos/actions/move_action.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protos import position_pb2 as common_dot_protos_dot_position__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'common/protos/actions/move_action.proto\x1a\x1c\x63ommon/protos/position.proto\".\n\nMoveAction\x12 \n\rgoal_position\x18\x01 \x01(\x0b\x32\t.Positionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.protos.actions.move_action_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOVEACTION']._serialized_start=73
  _globals['_MOVEACTION']._serialized_end=119
# @@protoc_insertion_point(module_scope)
